package com.project.pojo;
// Generated 24-Feb-2023, 5:28:10 pm by Hibernate Tools 5.4.33.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DoctorEstablishment generated by hbm2java
 */
public class DoctorEstablishment implements java.io.Serializable {

	private Integer eid;
	private char establishment;
	private String establishmentName;
	private String establishmentLocation;
	private String establishmentCity;
	private String establishmentProof;
	private String establishmentPin;
	private Date lastUpdated;
	private String extraCol1;
	private String extraCol2;
	private String extraCol3;
	private Set doctorPrimaries = new HashSet(0);

	public DoctorEstablishment() {
	}

	public DoctorEstablishment(char establishment, String establishmentName, String establishmentLocation,
			String establishmentCity, String establishmentProof, String establishmentPin, Date lastUpdated) {
		this.establishment = establishment;
		this.establishmentName = establishmentName;
		this.establishmentLocation = establishmentLocation;
		this.establishmentCity = establishmentCity;
		this.establishmentProof = establishmentProof;
		this.establishmentPin = establishmentPin;
		this.lastUpdated = lastUpdated;
	}

	public DoctorEstablishment(char establishment, String establishmentName, String establishmentLocation,
			String establishmentCity, String establishmentProof, String establishmentPin, Date lastUpdated,
			String extraCol1, String extraCol2, String extraCol3, Set doctorPrimaries) {
		this.establishment = establishment;
		this.establishmentName = establishmentName;
		this.establishmentLocation = establishmentLocation;
		this.establishmentCity = establishmentCity;
		this.establishmentProof = establishmentProof;
		this.establishmentPin = establishmentPin;
		this.lastUpdated = lastUpdated;
		this.extraCol1 = extraCol1;
		this.extraCol2 = extraCol2;
		this.extraCol3 = extraCol3;
		this.doctorPrimaries = doctorPrimaries;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public char getEstablishment() {
		return this.establishment;
	}

	public void setEstablishment(char establishment) {
		this.establishment = establishment;
	}

	public String getEstablishmentName() {
		return this.establishmentName;
	}

	public void setEstablishmentName(String establishmentName) {
		this.establishmentName = establishmentName;
	}

	public String getEstablishmentLocation() {
		return this.establishmentLocation;
	}

	public void setEstablishmentLocation(String establishmentLocation) {
		this.establishmentLocation = establishmentLocation;
	}

	public String getEstablishmentCity() {
		return this.establishmentCity;
	}

	public void setEstablishmentCity(String establishmentCity) {
		this.establishmentCity = establishmentCity;
	}

	public String getEstablishmentProof() {
		return this.establishmentProof;
	}

	public void setEstablishmentProof(String establishmentProof) {
		this.establishmentProof = establishmentProof;
	}

	public String getEstablishmentPin() {
		return this.establishmentPin;
	}

	public void setEstablishmentPin(String establishmentPin) {
		this.establishmentPin = establishmentPin;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public String getExtraCol1() {
		return this.extraCol1;
	}

	public void setExtraCol1(String extraCol1) {
		this.extraCol1 = extraCol1;
	}

	public String getExtraCol2() {
		return this.extraCol2;
	}

	public void setExtraCol2(String extraCol2) {
		this.extraCol2 = extraCol2;
	}

	public String getExtraCol3() {
		return this.extraCol3;
	}

	public void setExtraCol3(String extraCol3) {
		this.extraCol3 = extraCol3;
	}

	public Set getDoctorPrimaries() {
		return this.doctorPrimaries;
	}

	public void setDoctorPrimaries(Set doctorPrimaries) {
		this.doctorPrimaries = doctorPrimaries;
	}

}
