package com.project.pojo;
// Generated 24-Feb-2023, 5:28:10 pm by Hibernate Tools 5.4.33.Final

import java.util.Date;

/**
 * DoctorPrimary generated by hbm2java
 */
public class DoctorPrimary implements java.io.Serializable {

	private int doctorId;
	private Address address;
	private DoctorAvailMaster doctorAvailMaster;
	private DoctorEstablishment doctorEstablishment;
	private DoctorMedRegistration doctorMedRegistration;
	private SecurityQuestions securityQuestions;
	private String securityQuestionsAnswer;
	private String fname;
	private String lname;
	private String email;
	private String pwd;
	private String phoneNumber;
	private char gender;
	private String panCard;
	private String adhaarCard;
	private String specialization;
	private int yearOfExperience;
	private char profileStatus;
	private String profilePhoto;
	private Date lastUpdated;
	private String extraCol1;
	private String extraCol2;
	private String extraCol3;

	public DoctorPrimary() {
	}

	public DoctorPrimary(Address address, DoctorAvailMaster doctorAvailMaster, DoctorEstablishment doctorEstablishment,
			DoctorMedRegistration doctorMedRegistration, SecurityQuestions securityQuestions,
			String securityQuestionsAnswer, String fname, String lname, String email, String pwd, String phoneNumber,
			char gender, String panCard, String adhaarCard, String specialization, int yearOfExperience,
			char profileStatus) {
		this.address = address;
		this.doctorAvailMaster = doctorAvailMaster;
		this.doctorEstablishment = doctorEstablishment;
		this.doctorMedRegistration = doctorMedRegistration;
		this.securityQuestions = securityQuestions;
		this.securityQuestionsAnswer = securityQuestionsAnswer;
		this.fname = fname;
		this.lname = lname;
		this.email = email;
		this.pwd = pwd;
		this.phoneNumber = phoneNumber;
		this.gender = gender;
		this.panCard = panCard;
		this.adhaarCard = adhaarCard;
		this.specialization = specialization;
		this.yearOfExperience = yearOfExperience;
		this.profileStatus = profileStatus;
	}

	public DoctorPrimary(Address address, DoctorAvailMaster doctorAvailMaster, DoctorEstablishment doctorEstablishment,
			DoctorMedRegistration doctorMedRegistration, SecurityQuestions securityQuestions,
			String securityQuestionsAnswer, String fname, String lname, String email, String pwd, String phoneNumber,
			char gender, String panCard, String adhaarCard, String specialization, int yearOfExperience,
			char profileStatus, String profilePhoto, Date lastUpdated, String extraCol1, String extraCol2,
			String extraCol3) {
		this.address = address;
		this.doctorAvailMaster = doctorAvailMaster;
		this.doctorEstablishment = doctorEstablishment;
		this.doctorMedRegistration = doctorMedRegistration;
		this.securityQuestions = securityQuestions;
		this.securityQuestionsAnswer = securityQuestionsAnswer;
		this.fname = fname;
		this.lname = lname;
		this.email = email;
		this.pwd = pwd;
		this.phoneNumber = phoneNumber;
		this.gender = gender;
		this.panCard = panCard;
		this.adhaarCard = adhaarCard;
		this.specialization = specialization;
		this.yearOfExperience = yearOfExperience;
		this.profileStatus = profileStatus;
		this.profilePhoto = profilePhoto;
		this.lastUpdated = lastUpdated;
		this.extraCol1 = extraCol1;
		this.extraCol2 = extraCol2;
		this.extraCol3 = extraCol3;
	}

	public int getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(int doctorId) {
		this.doctorId = doctorId;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public DoctorAvailMaster getDoctorAvailMaster() {
		return this.doctorAvailMaster;
	}

	public void setDoctorAvailMaster(DoctorAvailMaster doctorAvailMaster) {
		this.doctorAvailMaster = doctorAvailMaster;
	}

	public DoctorEstablishment getDoctorEstablishment() {
		return this.doctorEstablishment;
	}

	public void setDoctorEstablishment(DoctorEstablishment doctorEstablishment) {
		this.doctorEstablishment = doctorEstablishment;
	}

	public DoctorMedRegistration getDoctorMedRegistration() {
		return this.doctorMedRegistration;
	}

	public void setDoctorMedRegistration(DoctorMedRegistration doctorMedRegistration) {
		this.doctorMedRegistration = doctorMedRegistration;
	}

	public SecurityQuestions getSecurityQuestions() {
		return this.securityQuestions;
	}

	public void setSecurityQuestions(SecurityQuestions securityQuestions) {
		this.securityQuestions = securityQuestions;
	}

	public String getSecurityQuestionsAnswer() {
		return this.securityQuestionsAnswer;
	}

	public void setSecurityQuestionsAnswer(String securityQuestionsAnswer) {
		this.securityQuestionsAnswer = securityQuestionsAnswer;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public char getGender() {
		return this.gender;
	}

	public void setGender(char gender) {
		this.gender = gender;
	}

	public String getPanCard() {
		return this.panCard;
	}

	public void setPanCard(String panCard) {
		this.panCard = panCard;
	}

	public String getAdhaarCard() {
		return this.adhaarCard;
	}

	public void setAdhaarCard(String adhaarCard) {
		this.adhaarCard = adhaarCard;
	}

	public String getSpecialization() {
		return this.specialization;
	}

	public void setSpecialization(String specialization) {
		this.specialization = specialization;
	}

	public int getYearOfExperience() {
		return this.yearOfExperience;
	}

	public void setYearOfExperience(int yearOfExperience) {
		this.yearOfExperience = yearOfExperience;
	}

	public char getProfileStatus() {
		return this.profileStatus;
	}

	public void setProfileStatus(char profileStatus) {
		this.profileStatus = profileStatus;
	}

	public String getProfilePhoto() {
		return this.profilePhoto;
	}

	public void setProfilePhoto(String profilePhoto) {
		this.profilePhoto = profilePhoto;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public String getExtraCol1() {
		return this.extraCol1;
	}

	public void setExtraCol1(String extraCol1) {
		this.extraCol1 = extraCol1;
	}

	public String getExtraCol2() {
		return this.extraCol2;
	}

	public void setExtraCol2(String extraCol2) {
		this.extraCol2 = extraCol2;
	}

	public String getExtraCol3() {
		return this.extraCol3;
	}

	public void setExtraCol3(String extraCol3) {
		this.extraCol3 = extraCol3;
	}

}
