package com.project.pojo;
// Generated 24-Feb-2023, 5:28:10 pm by Hibernate Tools 5.4.33.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DoctorMedRegistration generated by hbm2java
 */
public class DoctorMedRegistration implements java.io.Serializable {

	private Integer medicalRegId;
	private String registrationCouncil;
	private Date registrationYear;
	private String degree;
	private String college;
	private Date yearOfCompletion;
	private Date lastUpdated;
	private String extraCol1;
	private String extraCol2;
	private String extraCol3;
	private Set doctorPrimaries = new HashSet(0);

	public DoctorMedRegistration() {
	}

	public DoctorMedRegistration(String registrationCouncil, Date registrationYear, String degree, String college,
			Date yearOfCompletion) {
		this.registrationCouncil = registrationCouncil;
		this.registrationYear = registrationYear;
		this.degree = degree;
		this.college = college;
		this.yearOfCompletion = yearOfCompletion;
	}

	public DoctorMedRegistration(String registrationCouncil, Date registrationYear, String degree, String college,
			Date yearOfCompletion, Date lastUpdated, String extraCol1, String extraCol2, String extraCol3,
			Set doctorPrimaries) {
		this.registrationCouncil = registrationCouncil;
		this.registrationYear = registrationYear;
		this.degree = degree;
		this.college = college;
		this.yearOfCompletion = yearOfCompletion;
		this.lastUpdated = lastUpdated;
		this.extraCol1 = extraCol1;
		this.extraCol2 = extraCol2;
		this.extraCol3 = extraCol3;
		this.doctorPrimaries = doctorPrimaries;
	}

	public Integer getMedicalRegId() {
		return this.medicalRegId;
	}

	public void setMedicalRegId(Integer medicalRegId) {
		this.medicalRegId = medicalRegId;
	}

	public String getRegistrationCouncil() {
		return this.registrationCouncil;
	}

	public void setRegistrationCouncil(String registrationCouncil) {
		this.registrationCouncil = registrationCouncil;
	}

	public Date getRegistrationYear() {
		return this.registrationYear;
	}

	public void setRegistrationYear(Date registrationYear) {
		this.registrationYear = registrationYear;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public String getCollege() {
		return this.college;
	}

	public void setCollege(String college) {
		this.college = college;
	}

	public Date getYearOfCompletion() {
		return this.yearOfCompletion;
	}

	public void setYearOfCompletion(Date yearOfCompletion) {
		this.yearOfCompletion = yearOfCompletion;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public String getExtraCol1() {
		return this.extraCol1;
	}

	public void setExtraCol1(String extraCol1) {
		this.extraCol1 = extraCol1;
	}

	public String getExtraCol2() {
		return this.extraCol2;
	}

	public void setExtraCol2(String extraCol2) {
		this.extraCol2 = extraCol2;
	}

	public String getExtraCol3() {
		return this.extraCol3;
	}

	public void setExtraCol3(String extraCol3) {
		this.extraCol3 = extraCol3;
	}

	public Set getDoctorPrimaries() {
		return this.doctorPrimaries;
	}

	public void setDoctorPrimaries(Set doctorPrimaries) {
		this.doctorPrimaries = doctorPrimaries;
	}

}
