package com.project.pojo;
// Generated 24-Feb-2023, 5:28:10 pm by Hibernate Tools 5.4.33.Final

import java.util.Date;

/**
 * PatientLabReport generated by hbm2java
 */
public class PatientLabReport implements java.io.Serializable {

	private Integer labReportId;
	private PatientMedLog patientMedLog;
	private String labReportType;
	private String labReport;
	private Date lastUpdated;
	private String extraCol1;
	private String extraCol2;
	private String extraCol3;

	public PatientLabReport() {
	}

	public PatientLabReport(String labReportType, String labReport, Date lastUpdated) {
		this.labReportType = labReportType;
		this.labReport = labReport;
		this.lastUpdated = lastUpdated;
	}

	public PatientLabReport(PatientMedLog patientMedLog, String labReportType, String labReport, Date lastUpdated,
			String extraCol1, String extraCol2, String extraCol3) {
		this.patientMedLog = patientMedLog;
		this.labReportType = labReportType;
		this.labReport = labReport;
		this.lastUpdated = lastUpdated;
		this.extraCol1 = extraCol1;
		this.extraCol2 = extraCol2;
		this.extraCol3 = extraCol3;
	}

	public Integer getLabReportId() {
		return this.labReportId;
	}

	public void setLabReportId(Integer labReportId) {
		this.labReportId = labReportId;
	}

	public PatientMedLog getPatientMedLog() {
		return this.patientMedLog;
	}

	public void setPatientMedLog(PatientMedLog patientMedLog) {
		this.patientMedLog = patientMedLog;
	}

	public String getLabReportType() {
		return this.labReportType;
	}

	public void setLabReportType(String labReportType) {
		this.labReportType = labReportType;
	}

	public String getLabReport() {
		return this.labReport;
	}

	public void setLabReport(String labReport) {
		this.labReport = labReport;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public String getExtraCol1() {
		return this.extraCol1;
	}

	public void setExtraCol1(String extraCol1) {
		this.extraCol1 = extraCol1;
	}

	public String getExtraCol2() {
		return this.extraCol2;
	}

	public void setExtraCol2(String extraCol2) {
		this.extraCol2 = extraCol2;
	}

	public String getExtraCol3() {
		return this.extraCol3;
	}

	public void setExtraCol3(String extraCol3) {
		this.extraCol3 = extraCol3;
	}

}
