package com.project.pojo;
// Generated 24-Feb-2023, 5:28:10 pm by Hibernate Tools 5.4.33.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PatientMedLog generated by hbm2java
 */
public class PatientMedLog implements java.io.Serializable {

	private Integer medLogId;
	private PatientPrimary patientPrimary;
	private String prescription;
	private Date lastUpdated;
	private String extraCol1;
	private String extraCol2;
	private String extraCol3;
	private Set patientLabReports = new HashSet(0);

	public PatientMedLog() {
	}

	public PatientMedLog(String prescription, Date lastUpdated) {
		this.prescription = prescription;
		this.lastUpdated = lastUpdated;
	}

	public PatientMedLog(PatientPrimary patientPrimary, String prescription, Date lastUpdated, String extraCol1,
			String extraCol2, String extraCol3, Set patientLabReports) {
		this.patientPrimary = patientPrimary;
		this.prescription = prescription;
		this.lastUpdated = lastUpdated;
		this.extraCol1 = extraCol1;
		this.extraCol2 = extraCol2;
		this.extraCol3 = extraCol3;
		this.patientLabReports = patientLabReports;
	}

	public Integer getMedLogId() {
		return this.medLogId;
	}

	public void setMedLogId(Integer medLogId) {
		this.medLogId = medLogId;
	}

	public PatientPrimary getPatientPrimary() {
		return this.patientPrimary;
	}

	public void setPatientPrimary(PatientPrimary patientPrimary) {
		this.patientPrimary = patientPrimary;
	}

	public String getPrescription() {
		return this.prescription;
	}

	public void setPrescription(String prescription) {
		this.prescription = prescription;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public String getExtraCol1() {
		return this.extraCol1;
	}

	public void setExtraCol1(String extraCol1) {
		this.extraCol1 = extraCol1;
	}

	public String getExtraCol2() {
		return this.extraCol2;
	}

	public void setExtraCol2(String extraCol2) {
		this.extraCol2 = extraCol2;
	}

	public String getExtraCol3() {
		return this.extraCol3;
	}

	public void setExtraCol3(String extraCol3) {
		this.extraCol3 = extraCol3;
	}

	public Set getPatientLabReports() {
		return this.patientLabReports;
	}

	public void setPatientLabReports(Set patientLabReports) {
		this.patientLabReports = patientLabReports;
	}

}
