package com.project.pojo;
// Generated 24-Feb-2023, 5:28:10 pm by Hibernate Tools 5.4.33.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PatientMedRecord generated by hbm2java
 */
//@Entity
//@Table(name = "patient_med_record", catalog = "project23")
public class PatientMedRecord implements java.io.Serializable {

	private int uid;
	private String bloodPressure;
	private BigDecimal weight;
	private String sugarLevel;
	private String bloodGroup;
	private char disability;
	//private Date lastUpdatedDate;
	//private String insuranceId;
	//private String insuranceName;
	//private Date insuranceExpireDate;
	//private String abhaNumber;
	//private String extCol1;
	//private String extCol2;
	//private String extCol3;
	//private PatientPrimary patientPrimary;

	public PatientMedRecord() {
	}

	public PatientMedRecord(int uid, String bloodPressure, BigDecimal weight, String sugarLevel, String bloodGroup,
			char disability) {
		this.uid = uid;
		this.bloodPressure = bloodPressure;
		this.weight = weight;
		this.sugarLevel = sugarLevel;
		this.bloodGroup = bloodGroup;
		this.disability = disability;
	}

	public PatientMedRecord(int uid, String bloodPressure, BigDecimal weight, String sugarLevel, String bloodGroup,
			char disability, Date lastUpdatedDate, String insuranceId, String insuranceName, Date insuranceExpireDate,
			String abhaNumber, String extCol1, String extCol2, String extCol3, PatientPrimary patientPrimary) {
		this.uid = uid;
		this.bloodPressure = bloodPressure;
		this.weight = weight;
		this.sugarLevel = sugarLevel;
		this.bloodGroup = bloodGroup;
		this.disability = disability;
		//this.lastUpdatedDate = lastUpdatedDate;
		//this.insuranceId = insuranceId;
		//this.insuranceName = insuranceName;
		//this.insuranceExpireDate = insuranceExpireDate;
		//this.abhaNumber = abhaNumber;
		//this.extCol1 = extCol1;
		//this.extCol2 = extCol2;
		//this.extCol3 = extCol3;
		//this.patientPrimary = patientPrimary;
	}
	//@Column(name = "UID", unique = true, nullable = false)
	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}
	//@Column(name = "BLOOD_PRESSURE", nullable = false)
	public String getBloodPressure() {
		return this.bloodPressure;
	}

	public void setBloodPressure(String bloodPressure) {
		this.bloodPressure = bloodPressure;
	}

	//@Column(name = "WEIGHT", nullable = false)
	public BigDecimal getWeight() {
		return this.weight;
	}
	
	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}
	//@Column(name = "SUGAR_LEVEL", nullable = false)
	public String getSugarLevel() {
		return this.sugarLevel;
	}

	public void setSugarLevel(String sugarLevel) {
		this.sugarLevel = sugarLevel;
	}
	//@Column(name = "BLOOD_GROUP", nullable = false)
	public String getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}
	//@Column(name = "DISABILITY", nullable = false)
	public char getDisability() {
		return this.disability;
	}

	public void setDisability(char disability) {
		this.disability = disability;
		}
	
	/*
	 * public Date getLastUpdatedDate() { return this.lastUpdatedDate; }
	 * 
	 * public void setLastUpdatedDate(Date lastUpdatedDate) { this.lastUpdatedDate =
	 * lastUpdatedDate; }
	 * 
	 * public String getInsuranceId() { return this.insuranceId; }
	 * 
	 * public void setInsuranceId(String insuranceId) { this.insuranceId =
	 * insuranceId; }
	 * 
	 * public String getInsuranceName() { return this.insuranceName; }
	 * 
	 * public void setInsuranceName(String insuranceName) { this.insuranceName =
	 * insuranceName; }
	 * 
	 * public Date getInsuranceExpireDate() { return this.insuranceExpireDate; }
	 * 
	 * public void setInsuranceExpireDate(Date insuranceExpireDate) {
	 * this.insuranceExpireDate = insuranceExpireDate; }
	 * 
	 * public String getAbhaNumber() { return this.abhaNumber; }
	 * 
	 * public void setAbhaNumber(String abhaNumber) { this.abhaNumber = abhaNumber;
	 * }
	 * 
	 * public String getExtCol1() { return this.extCol1; }
	 * 
	 * public void setExtCol1(String extCol1) { this.extCol1 = extCol1; }
	 * 
	 * public String getExtCol2() { return this.extCol2; }
	 * 
	 * public void setExtCol2(String extCol2) { this.extCol2 = extCol2; }
	 * 
	 * public String getExtCol3() { return this.extCol3; }
	 * 
	 * public void setExtCol3(String extCol3) { this.extCol3 = extCol3; }
	 * 
	 * public PatientPrimary getPatientPrimary() { return this.patientPrimary; }
	 * 
	 * public void setPatientPrimary(PatientPrimary patientPrimary) {
	 * this.patientPrimary = patientPrimary; }
	 */
}
