package com.project.pojo;
// Generated 24-Feb-2023, 5:28:10 pm by Hibernate Tools 5.4.33.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SecurityQuestions generated by hbm2java
 */
public class SecurityQuestions implements java.io.Serializable {

	private Integer securityQuestionsId;
	private String securityQuestion;
	private Date lastUpdated;
	private String extraCol1;
	private String extraCol2;
	private String extraCol3;
	private Set patientPrimaries = new HashSet(0);
	private Set doctorPrimaries = new HashSet(0);

	public SecurityQuestions() {
	}

	public SecurityQuestions(String securityQuestion) {
		this.securityQuestion = securityQuestion;
	}

	public SecurityQuestions(String securityQuestion, Date lastUpdated, String extraCol1, String extraCol2,
			String extraCol3, Set patientPrimaries, Set doctorPrimaries) {
		this.securityQuestion = securityQuestion;
		this.lastUpdated = lastUpdated;
		this.extraCol1 = extraCol1;
		this.extraCol2 = extraCol2;
		this.extraCol3 = extraCol3;
		this.patientPrimaries = patientPrimaries;
		this.doctorPrimaries = doctorPrimaries;
	}

	public Integer getSecurityQuestionsId() {
		return this.securityQuestionsId;
	}

	public void setSecurityQuestionsId(Integer securityQuestionsId) {
		this.securityQuestionsId = securityQuestionsId;
	}

	public String getSecurityQuestion() {
		return this.securityQuestion;
	}

	public void setSecurityQuestion(String securityQuestion) {
		this.securityQuestion = securityQuestion;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public String getExtraCol1() {
		return this.extraCol1;
	}

	public void setExtraCol1(String extraCol1) {
		this.extraCol1 = extraCol1;
	}

	public String getExtraCol2() {
		return this.extraCol2;
	}

	public void setExtraCol2(String extraCol2) {
		this.extraCol2 = extraCol2;
	}

	public String getExtraCol3() {
		return this.extraCol3;
	}

	public void setExtraCol3(String extraCol3) {
		this.extraCol3 = extraCol3;
	}

	public Set getPatientPrimaries() {
		return this.patientPrimaries;
	}

	public void setPatientPrimaries(Set patientPrimaries) {
		this.patientPrimaries = patientPrimaries;
	}

	public Set getDoctorPrimaries() {
		return this.doctorPrimaries;
	}

	public void setDoctorPrimaries(Set doctorPrimaries) {
		this.doctorPrimaries = doctorPrimaries;
	}

}
