package com.project.entity;
// Generated 03-Mar-2023, 8:40:48 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AdminPrimary generated by hbm2java
 */
@Entity
@Table(name = "admin_primary", uniqueConstraints = @UniqueConstraint(columnNames = "Email"))
public class AdminPrimary implements java.io.Serializable {

	private Integer adminId;
	private String email;
	private String pwd;
	private Date lastUpdatedDate;
	//private String extCol1;
	//private String extCol2;
	//private String extCol3;

	public AdminPrimary() {
	}

	public AdminPrimary(String email, String pwd) {
		this.email = email;
		this.pwd = pwd;
	}

	public AdminPrimary(String email, String pwd, Date lastUpdatedDate, String extCol1, String extCol2,
			String extCol3) {
		this.email = email;
		this.pwd = pwd;
		this.lastUpdatedDate = lastUpdatedDate;
		//this.extCol1 = extCol1;
		//this.extCol2 = extCol2;
		//this.extCol3 = extCol3;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Admin_ID", unique = true, nullable = false)
	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	@Column(name = "Email", unique = true, nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Pwd", nullable = false, length = 50)
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Last_Updated_Date", length = 19)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	/*
	 * @Column(name = "Ext_Col_1", length = 100) public String getExtCol1() { return
	 * this.extCol1; }
	 * 
	 * public void setExtCol1(String extCol1) { this.extCol1 = extCol1; }
	 * 
	 * @Column(name = "Ext_Col_2", length = 100) public String getExtCol2() { return
	 * this.extCol2; }
	 * 
	 * public void setExtCol2(String extCol2) { this.extCol2 = extCol2; }
	 * 
	 * @Column(name = "Ext_Col_3", length = 100) public String getExtCol3() { return
	 * this.extCol3; }
	 * 
	 * public void setExtCol3(String extCol3) { this.extCol3 = extCol3; }
	 */
}
