package com.project.entity;
// Generated 03-Mar-2023, 8:40:48 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SecurityQuestions generated by hbm2java
 */
@Entity
@Table(name = "security_questions")
public class SecurityQuestions implements java.io.Serializable {

	private int securityQuestionsId;
	private String securityQuestion;
	private Date lastUpdated;
	//private String extraCol1;
	//private String extraCol2;
	//private String extraCol3;
	//private Set patientPrimaries = new HashSet(0);
	//private Set doctorPrimaries = new HashSet(0);

	public SecurityQuestions() {
	}

	public SecurityQuestions(int securityQuestionsId, String securityQuestion) {
		this.securityQuestionsId = securityQuestionsId;
		this.securityQuestion = securityQuestion;
	}

	public SecurityQuestions(int securityQuestionsId, String securityQuestion, Date lastUpdated, String extraCol1,
			String extraCol2, String extraCol3, Set patientPrimaries, Set doctorPrimaries) {
		this.securityQuestionsId = securityQuestionsId;
		this.securityQuestion = securityQuestion;
		this.lastUpdated = lastUpdated;
		//this.extraCol1 = extraCol1;
		//this.extraCol2 = extraCol2;
		//this.extraCol3 = extraCol3;
		//this.patientPrimaries = patientPrimaries;
		//this.doctorPrimaries = doctorPrimaries;
	}

	@Id

	@Column(name = "SECURITY_QUESTIONS_ID", unique = true, nullable = false)
	public int getSecurityQuestionsId() {
		return this.securityQuestionsId;
	}

	public void setSecurityQuestionsId(int securityQuestionsId) {
		this.securityQuestionsId = securityQuestionsId;
	}

	@Column(name = "SECURITY_QUESTION", nullable = false, length = 50)
	public String getSecurityQuestion() {
		return this.securityQuestion;
	}

	public void setSecurityQuestion(String securityQuestion) {
		this.securityQuestion = securityQuestion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}
	/*
	 * @Column(name = "EXTRA_COL1", length = 200) public String getExtraCol1() {
	 * return this.extraCol1; }
	 * 
	 * public void setExtraCol1(String extraCol1) { this.extraCol1 = extraCol1; }
	 * 
	 * @Column(name = "EXTRA_COL2", length = 200) public String getExtraCol2() {
	 * return this.extraCol2; }
	 * 
	 * public void setExtraCol2(String extraCol2) { this.extraCol2 = extraCol2; }
	 * 
	 * @Column(name = "EXTRA_COL3", length = 200) public String getExtraCol3() {
	 * return this.extraCol3; }
	 * 
	 * public void setExtraCol3(String extraCol3) { this.extraCol3 = extraCol3; }
	 * 
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "securityQuestions") public Set
	 * getPatientPrimaries() { return this.patientPrimaries; }
	 * 
	 * public void setPatientPrimaries(Set patientPrimaries) { this.patientPrimaries
	 * = patientPrimaries; }
	 * 
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "securityQuestions") public Set
	 * getDoctorPrimaries() { return this.doctorPrimaries; }
	 * 
	 * public void setDoctorPrimaries(Set doctorPrimaries) { this.doctorPrimaries =
	 * doctorPrimaries; }
	 */

}
